-- MySQL Script generated by MySQL Workbench
-- mié 03 may 2023 14:53:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema my_portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_portfolio` DEFAULT CHARACTER SET utf8 ;
USE `my_portfolio` ;

-- -----------------------------------------------------
-- Table `my_portfolio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`persona` (
  `id_persona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(200) NULL DEFAULT NULL,
  `imagen` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `my_portfolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`educacion` (
  `id_educacion` INT NOT NULL,
  `nombre_titulo` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_comienzo` DATE NULL DEFAULT NULL,
  `fecha_finalizacion` DATE NULL DEFAULT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_educacion`, `persona_id_persona`),
  INDEX `fk_educacion_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `my_portfolio`.`persona` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `my_portfolio`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`experiencia` (
  `id_experiencia` INT NOT NULL,
  `nombre_empresa` VARCHAR(45) NULL DEFAULT NULL,
  `cargo_ocupado` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_experiencia`, `persona_id_persona`),
  INDEX `fk_experiencia_persona_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_persona`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `my_portfolio`.`persona` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `my_portfolio`.`habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`habilidad` (
  `id_habilidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_herramienta` VARCHAR(45) NULL DEFAULT NULL,
  `nivel` FLOAT NULL DEFAULT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_habilidad`, `persona_id_persona`),
  INDEX `fk_habilidad_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_habilidad_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `my_portfolio`.`persona` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `my_portfolio`.`habilidad_seq`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`habilidad_seq` (
  `next_val` BIGINT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `my_portfolio`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`proyecto` (
  `id_proyecto` INT NOT NULL,
  `nombre_proyecto` VARCHAR(45) NULL DEFAULT NULL,
  `año` INT NULL DEFAULT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_proyecto`, `persona_id_persona`),
  INDEX `fk_proyecto_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `my_portfolio`.`persona` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `my_portfolio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`usuario` (
  `id_usuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `contraseña_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `persona_id_persona`),
  INDEX `fk_usuario_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `my_portfolio`.`persona` (`id_persona`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
