-- MySQL Script generated by MySQL Workbench
-- vie 17 feb 2023 21:08:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema my_portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema my_portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `my_portfolio` ;
USE `my_portfolio` ;

-- -----------------------------------------------------
-- Table `my_portfolio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`persona` (
  `id_persona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  `imagen` VARCHAR(200) NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_portfolio`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`experiencia` (
  `id_experiencia` INT NOT NULL,
  `nombre_empresa` VARCHAR(45) NULL,
  `cargo_ocupado` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_experiencia`, `persona_id_persona`),
  INDEX `fk_experiencia_persona_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_persona`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `my_portfolio`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_portfolio`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`educacion` (
  `id_educacion` INT NOT NULL,
  `nombre_titulo` VARCHAR(45) NULL,
  `fecha_comienzo` DATE NULL,
  `fecha_finalizacion` DATE NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_educacion`, `persona_id_persona`),
  INDEX `fk_educacion_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `my_portfolio`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_portfolio`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`proyecto` (
  `id_proyecto` INT NOT NULL,
  `nombre_proyecto` VARCHAR(45) NULL,
  `año` DATE NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_proyecto`, `persona_id_persona`),
  INDEX `fk_proyecto_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `my_portfolio`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `my_portfolio`.`habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `my_portfolio`.`habilidad` (
  `id_habilidad` INT NOT NULL,
  `nombre_herramienta` VARCHAR(45) NULL,
  `nivel` VARCHAR(45) NULL,
  `persona_id_persona` INT NOT NULL,
  PRIMARY KEY (`id_habilidad`, `persona_id_persona`),
  INDEX `fk_habilidad_persona1_idx` (`persona_id_persona` ASC) VISIBLE,
  CONSTRAINT `fk_habilidad_persona1`
    FOREIGN KEY (`persona_id_persona`)
    REFERENCES `my_portfolio`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
